import React from 'react';

class SmithingExperience extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            experience: {},
        };

        this.experience = {
            Tasks: [
                { Name: 'Bronze bar', Level: 1, XP: 6.25 },
                { Name: 'Bronze axe', Level: 1, XP: 12.5 },
                { Name: 'Bronze dagger', Level: 1, XP: 12.5 },
                { Name: 'Bronze mace', Level: 2, XP: 12.5 },                
                { Name: 'Bronze med helm', Level: 3, XP: 12.5 },
                { Name: 'Bronze bolts (unf)', Level: 3, XP: 12.5 },
                { Name: 'Bronze nails', Level: 4, XP: 12.5 },
                { Name: 'Bronze sword', Level: 4, XP: 12.5 },
                { Name: 'Bronze wire', Level: 4, XP: 12.5 },
                { Name: 'Bronze dart tip', Level: 4, XP: 12.5 },
                { Name: 'Bronze arrowtips', Level: 5, XP: 12.5 },
                { Name: 'Bronze scimitar', Level: 5, XP: 25 },
                { Name: 'Bronze javelin heads', Level: 6, XP: 12.5 },
                { Name: 'Bronze longsword', Level: 6, XP: 25 },        
                { Name: 'Bronze limbs', Level: 6, XP: 12.5 },
                { Name: 'Bronze knife', Level: 7, XP: 12.5 },
                { Name: 'Bronze full helm', Level: 7, XP: 25 },
                { Name: 'Bronze sq shield', Level: 8, XP: 25 },
                { Name: 'Bronze warhammer', Level: 9, XP: 37.5 },
                { Name: 'Bronze battleaxe', Level: 10, XP: 37.5 },
                { Name: 'Bronze chainbody', Level: 11, XP: 37.5 },
                { Name: 'Bronze kiteshield', Level: 12, XP: 37.5 },
                { Name: 'Bronze claws', Level: 13, XP: 25 },
                { Name: 'Bronze 2h sword', Level: 14, XP: 37.5 }, 
                { Name: 'Iron bar', Level: 15, XP: 12.5 },              
                { Name: 'Iron dagger', Level: 15, XP: 25 },
                { Name: 'Iron axe', Level: 16, XP: 25 },
                { Name: 'Bronze platelegs', Level: 16, XP: 37.5 },
                { Name: 'Bronze plateskirt', Level: 16, XP: 37.5 },
                { Name: 'Iron spit', Level: 17, XP: 25 },
                { Name: 'Iron mace', Level: 17, XP: 25 },       
                { Name: 'Bronze platebody', Level: 18, XP: 62.5 },          
                { Name: 'Iron med helm', Level: 18, XP: 25 },
                { Name: 'Iron bolts (unf)', Level: 18, XP: 25 },
                { Name: 'Iron nails', Level: 19, XP: 25 },                
                { Name: 'Iron dart tip', Level: 19, XP: 25 },
                { Name: 'Iron sword', Level: 19, XP: 25 },
                { Name: 'Silver bar', Level: 20, XP: 13.7 },
                { Name: 'Iron arrowtips', Level: 20, XP: 25 },               
                { Name: 'Iron scimitar', Level: 20, XP: 50 },                
                { Name: 'Iron javelin heads', Level: 21, XP: 50 },
                { Name: 'Iron longsword', Level: 21, XP: 50 },                  
                { Name: 'Iron knife', Level: 22, XP: 25 },
                { Name: 'Iron full helm', Level: 22, XP: 50 },      
                { Name: 'Iron limbs', Level: 23, XP: 25 },
                { Name: 'Iron sq shield', Level: 23, XP: 50 },
                { Name: 'Iron warhammer', Level: 24, XP: 75 },
                { Name: 'Iron battleaxe', Level: 25, XP: 75 },
                { Name: 'Oil lantern frame', Level: 25, XP: 25 },
                { Name: 'Iron chainbody', Level: 26, XP: 75 },
                { Name: 'Iron kiteshield', Level: 27, XP: 75 },
                { Name: 'Iron claws', Level: 28, XP: 5 },
                { Name: 'Iron 2h sword', Level: 29, XP: 75 },
                { Name: 'Steel bar', Level: 30, XP: 17.5 },              
                { Name: 'Steel dagger', Level: 30, XP: 37.5 },
                { Name: 'Iron platelegs', Level: 31, XP: 75 },
                { Name: 'Iron plateskirt', Level: 31, XP: 75 },
                { Name: 'Steel axe', Level: 31, XP: 37.5 },
                { Name: 'Steel mace', Level: 32, XP: 37.5 },       
                { Name: 'Iron platebody', Level: 33, XP: 125 },    
                { Name: 'Steel med helm', Level: 33, XP: 37.5 },
                { Name: 'Steel bolts (unf)', Level: 33, XP: 37.5 },
                { Name: 'Steel nails', Level: 34, XP: 37.5 },                
                { Name: 'Steel dart tip', Level: 34, XP: 37.5},
                { Name: 'Steel sword', Level: 34, XP: 37.5},
                { Name: 'Cannonball', Level: 35, XP: 25.6 },
                { Name: 'Steel scimitar', Level: 35, XP: 75 },   
                { Name: 'Steel arrowtips', Level: 35, XP: 37.5 },               
                { Name: 'Steel limbs', Level: 36, XP: 37.5 },  
                { Name: 'Steel studs', Level: 36, XP: 37.5 },  
                { Name: 'Steel javelin heads', Level: 36, XP: 37.5 },
                { Name: 'Steel longsword', Level: 36, XP: 37.5 },             
                { Name: 'Steel knife', Level: 37, XP: 37.5 },
                { Name: 'Steel full helm', Level: 37, XP: 75 },     
                { Name: 'Steel sq shield', Level: 38, XP: 50 },
                { Name: 'Steel warhammer', Level: 39, XP: 112.5 },
                { Name: 'Steel battleaxe', Level: 40, XP: 112.5 },
                { Name: 'Gold bar (blast furance)', Level: 40, XP: 56.2 },
                { Name: 'Gold bar', Level: 40, XP: 22.5 },
                { Name: 'Steel chainbody', Level: 41, XP: 112.5 },
                { Name: 'Steel kiteshield', Level: 42, XP: 112.5 },
                { Name: 'Steel claws', Level: 43, XP: 75 },
                { Name: 'Steel 2h sword', Level: 44, XP: 112.5 },
                { Name: 'Steel platelegs', Level: 46, XP: 112.5 },
                { Name: 'Steel plateskirt', Level: 46, XP: 112.5 },
                { Name: 'Steel platebody', Level: 48, XP: 187.5 }, 
                { Name: 'Bullseye lantern (unf)', Level: 49, XP: 37.5 },                
                { Name: 'Mithril bar', Level: 50, XP: 50 },              
                { Name: 'Mithril dagger', Level: 50, XP: 50 }, 
                { Name: 'Mithril axe', Level: 51, XP: 37.5 },
                { Name: 'Mithril mace', Level: 52, XP: 37.5 },               
                { Name: 'Mithril med helm', Level: 33, XP: 50 },
                { Name: 'Mithril bolts (unf)', Level: 33, XP: 50 },
                { Name: 'Mithril nails', Level: 54, XP: 50 },                
                { Name: 'Mithril dart tip', Level: 54, XP: 50},
                { Name: 'Mithril sword', Level: 54, XP: 50},
                { Name: 'Mithril scimitar', Level: 55, XP: 100 },   
                { Name: 'Mithril arrowtips', Level: 55, XP: 50 },               
                { Name: 'Mithril limbs', Level: 56, XP: 50 },   
                { Name: 'Mithril javelin heads', Level: 56, XP: 50 },
                { Name: 'Mithril longsword', Level: 56, XP: 100 },             
                { Name: 'Mithril knife', Level: 57, XP: 50 },
                { Name: 'Mithril full helm', Level: 57, XP: 100 },     
                { Name: 'Mithril sq shield', Level: 58, XP: 100 },
                { Name: 'Mithril warhammer', Level: 59, XP: 150 },
                { Name: 'Mithril battleaxe', Level: 60, XP: 150 },
                { Name: 'Dragon sq shield', Level: 60, XP: 75 },
                { Name: 'Mithril chainbody', Level: 61, XP: 150 },
                { Name: 'Mithril kiteshield', Level: 62, XP: 150 },
                { Name: 'Mithril claws', Level: 63, XP: 100 },
                { Name: 'Mithril 2h sword', Level: 64, XP: 150 },
                { Name: 'Mithril platelegs', Level: 66, XP: 150 },
                { Name: 'Mithril plateskirt', Level: 66, XP: 150 },
                { Name: 'Mithril platebody', Level: 68, XP: 250 }, 
                { Name: 'Adamant bar', Level: 70, XP: 37.5 },              
                { Name: 'Adamant dagger', Level: 70, XP: 62.5 }, 
                { Name: 'Adamant axe', Level: 71, XP: 62.5 },
                { Name: 'Adamant mace', Level: 72, XP: 62.5 },   
                { Name: 'Adamant med helm', Level: 73, P: 62.5 },
                { Name: 'Adamant bolts (unf)', Level: 73, XP: 62.5 },
                { Name: 'Adamant nails', Level: 74, XP: 62.5 },                
                { Name: 'Adamant dart tip', Level: 74, XP: 62.5},
                { Name: 'Adamant sword', Level: 74, XP: 62.5},
                { Name: 'Adamant scimitar', Level: 75, XP: 125 },   
                { Name: 'Adamant arrowtips', Level: 75, XP: 62.5 },               
                { Name: 'Adamant limbs', Level: 76, XP: 62.5 },   
                { Name: 'Adamant javelin heads', Level: 76, XP: 62.5 },
                { Name: 'Adamant longsword', Level: 76, XP: 125 },             
                { Name: 'Adamant knife', Level: 77, XP: 50 },
                { Name: 'Adamant full helm', Level: 77, XP: 125 },     
                { Name: 'Adamant sq shield', Level: 78, XP: 125 },
                { Name: 'Adamant warhammer', Level: 79, XP: 187.5 },
                { Name: 'Adamant battleaxe', Level: 80, XP: 187.5 },
                { Name: 'Adamant chainbody', Level: 81, XP: 187.5 },
                { Name: 'Adamant kiteshield', Level: 82, XP: 187.5 },
                { Name: 'Adamant claws', Level: 83, XP: 125 },
                { Name: 'Adamant 2h sword', Level: 84, XP: 187.5 },
                { Name: 'Runite bar', Level: 85, XP: 50 },              
                { Name: 'Runite dagger', Level: 85, XP: 75 }, 
                { Name: 'Runite axe', Level: 85, XP: 75 },
                { Name: 'Adamant platelegs', Level: 86, XP: 187.5 },
                { Name: 'Adamant plateskirt', Level: 86, XP: 187.5 },
                { Name: 'Runite mace', Level: 87, XP: 75 },               
                { Name: 'Runite med helm', Level: 88, XP: 75 },
                { Name: 'Runite bolts (unf)', Level: 88, XP: 75 },
                { Name: 'Adamant platebody', Level: 88, XP: 312.5 }, 
                { Name: 'Runite sword', Level: 89, XP: 75},
                { Name: 'Runite nails', Level: 89, XP: 75},
                { Name: 'Runite dart tip', Level: 89, XP: 75},
                { Name: 'Runite scimitar', Level: 90, XP: 150 },   
                { Name: 'Dragonfire shield', Level: 90, XP: 2000 }, 
                { Name: 'Runite arrowtips', Level: 90, XP: 75 },          
                { Name: 'Runite limbs', Level: 91, XP: 75 },   
                { Name: 'Runite javelin heads', Level: 91, XP: 75 },
                { Name: 'Runite longsword', Level: 91, XP: 100 },             
                { Name: 'Runite knife', Level: 92, XP: 50 },
                { Name: 'Runite full helm', Level: 92, XP: 150 },     
                { Name: 'Runite sq shield', Level: 93, XP: 150 },
                { Name: 'Runite warhammer', Level: 94, XP: 225 },
                { Name: 'Runite battleaxe', Level: 95, XP: 225 },
                { Name: 'Runite chainbody', Level: 96, XP: 225 },
                { Name: 'Runite kiteshield', Level: 97, XP: 225 },
                { Name: 'Runite claws', Level: 98, XP: 150 },
                { Name: 'Runite 2h sword', Level: 99, XP: 225 },
                { Name: 'Runite platelegs', Level: 99, XP: 225 },
                { Name: 'Runite plateskirt', Level: 99, XP: 225 },
                { Name: 'Runite platebody', Level: 99, XP: 375 }, 
            ]
        };
    }
    
    getSmithingExperienceTable() {
        return this.experience;
    }

	
    
}
const smithingXP = new SmithingExperience();
export default smithingXP;