import React from 'react';

class MagicExperience extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            experience: {},
        };

        this.experience = {
            Tasks: [
                { Name: 'Wind Strike', Level: 1, XP: 5.5 },
                { Name: 'Reanimate Goblin', Level: 3, XP: 6 },
                { Name: 'Confuse', Level: 3, XP: 13 },
                { Name: 'Enchant Opal Bolt', Level: 4, XP: 9 },
                { Name: 'Water Strike', Level: 5, XP: 7.5 },
                { Name: 'Lumbridge Graveyard Teleport', Level: 6, XP: 10 },
                { Name: 'Enchant Sapphire Jewellery', Level: 7, XP: 17.5 },
                { Name: 'Enchant Sapphire Bolt', Level: 7, XP: 17.5 },
                { Name: 'Reanimate Monkey', Level: 7, XP: 14 },
                { Name: 'Earth Strike', Level: 9, XP: 9.5 },
                { Name: 'Weaken', Level: 11, XP: 21 },
                { Name: 'Reanimate Imp', Level: 12, XP: 24 },
                { Name: 'Fire Strike', Level: 13, XP: 11.5 },
                { Name: 'Enchant Jade Bolt', Level: 14, XP: 19 },
                { Name: 'Bones to Bananas', Level: 15, XP: 25 },
                { Name: 'Reanimate Minotaur', Level: 16, XP: 32 },
                { Name: 'Draynor Manor Teleport', Level: 17, XP: 16 },
                { Name: 'Wind Bolt', Level: 17, XP: 13.5 },
                { Name: 'Reanimate Scorpion', Level: 19, XP: 38 },
                { Name: 'Curse', Level: 19, XP: 29 },
                { Name: 'Bind', Level: 20, XP: 30 },
                { Name: 'Low Level Alchemy', Level: 21, XP: 31 },
                { Name: 'Reanimate Bear', Level: 21, XP: 42 },
                { Name: 'Reanimate Unicorn', Level: 22, XP: 44 },
                { Name: 'Water Bolt', Level: 23, XP: 16.5 },
                { Name: 'Enchant Pearl Bolt', Level: 24, XP: 29 },
                { Name: 'Varrock Teleport', Level: 25, XP: 35 },
                { Name: 'Reanimate Dog', Level: 26, XP: 52 },
                { Name: 'Enchant Emerald Jewellery', Level: 27, XP: 37 },
                { Name: 'Enchant Emerald Bolt', Level: 27, XP: 37 },
                { Name: 'Mind Altar Teleport', Level: 28, XP: 22 },
                { Name: 'Enchant Topaz Bolt ', Level: 29, XP: 33 },
                { Name: '	Earth Bolt', Level: 29, XP: 19.5 },
                { Name: 'Reanimate Chaos Druid', Level: 30, XP: 60 },
                { Name: 'Lumbridge Teleport', Level: 31, XP: 41 },
                { Name: 'Telekinetic Grab', Level: 33, XP: 43 },
                { Name: 'Respawn Teleport', Level: 34, XP: 27 },
                { Name: 'Fire Bolt', Level: 35, XP: 22.5 },
                { Name: 'Reanimate Giant', Level: 37, XP: 74 },
                { Name: 'Falador Teleport', Level: 37, XP: 48 },
                { Name: 'Crumble Undead', Level: 39, XP: 24.5 },
                { Name: 'Salve Graveyard Teleport', Level: 40, XP: 30 },
                { Name: 'Reanimate Ogre', Level: 40, XP: 80 },
                { Name: 'Teleport to House ', Level: 40, XP: 30 },
                { Name: 'Wind Blast', Level: 41, XP: 25.5 },
                { Name: 'Superheat Item', Level: 43, XP: 53 },
                { Name: 'Reanimate Elf', Level: 43, XP: 86 },
                { Name: 'Camelot Teleport', Level: 45, XP: 55.5 },
                { Name: 'Reanimate Troll', Level: 46, XP: 92 },
                { Name: 'Water Blast', Level: 47, XP: 28.5 },
                { Name: 'Fenkenstrains Castle Teleport', Level: 48, XP: 50 },
                { Name: 'Enchant Ruby Jewellery', Level: 49, XP: 59 },
                { Name: 'Enchant Ruby Bolt', Level: 49, XP: 59 },
                { Name: 'Iban Blast', Level: 50, XP: 30 },
                { Name: 'Smoke Rush', Level: 50, XP: 30 },
                { Name: 'Magic Dart', Level: 50, XP: 30 },
                { Name: 'Snare', Level: 50, XP: 60 },
                { Name: 'Ardougne Teleport', Level: 51, XP: 61 },
                { Name: 'Reanimate Horror', Level: 52, XP: 104 },
                { Name: 'Shadow Rush', Level: 52, XP: 31 },
                { Name: 'Earth Blast', Level: 53, XP: 31.5 },
                { Name: 'Paddewwa Teleport', Level: 54, XP: 64 },
                { Name: 'High Level Alchemy', Level: 55, XP: 65 },
                { Name: 'Charge Water Orb', Level: 56, XP: 56 },
                { Name: 'Blood Rush', Level: 56, XP: 33 },
                { Name: 'Enchant Diamond Bolt', Level: 57, XP: 67 },
                { Name: 'Enchant Diamond Jewellery', Level: 57, XP: 67 },
                { Name: 'Reanimate Kalphite', Level: 57, XP: 114 },
                { Name: 'Watchtower Teleport', Level: 58, XP: 68 },
                { Name: 'Ice Rush', Level: 58, XP: 34 },
                { Name: 'Fire Blast', Level: 59, XP: 34.5 },
                { Name: 'Senntisten Teleport', Level: 60, XP: 70 },
                { Name: 'Claws of Guthix', Level: 60, XP: 35 },
                { Name: 'Flames of Zamorak', Level: 60, XP: 35 },
                { Name: 'Saradomin Strike', Level: 60, XP: 35 },
                { Name: 'Charge Earth Orb', Level: 60, XP: 70 },
                { Name: 'Bones to Peaches', Level: 60, XP: 65 },
                { Name: 'West Ardougne Teleport', Level: 61, XP: 68 },
                { Name: 'Trollheim Teleport', Level: 61, XP: 68 },
                { Name: 'Reanimate Dagannoth', Level: 62, XP: 124 },
                { Name: 'Smoke Burst', Level: 62, XP: 36 },
                { Name: 'Wind Wave', Level: 62, XP: 36 },
                { Name: 'Charge Fire Orb', Level: 63, XP: 73 },
                { Name: 'Shadow Burst', Level: 64, XP: 37 },
                { Name: 'Teleport Ape Atoll', Level: 64, XP: 74 },
                { Name: 'Bake Pie', Level: 65, XP: 60 },
                { Name: 'Harmony Island Teleport', Level: 65, XP: 74 },
                { Name: 'Reanimate Bloodveld', Level: 65, XP: 130 },
                { Name: 'Geomancy', Level: 65, XP: 60 },
                { Name: 'Water Wave', Level: 65, XP: 37.5 },
                { Name: 'Charge Air Orb', Level: 66, XP: 76 },
                { Name: 'Cure Plant', Level: 66, XP: 60 },
                { Name: 'Kharyrll Teleport', Level: 66, XP: 76 },
                { Name: 'Vulnerability', Level: 66, XP: 76 },
                { Name: 'Monster Examine', Level: 66, XP: 61 },
                { Name: 'NPC Contact', Level: 67, XP: 63 },
                { Name: 'Blood Burst', Level: 68, XP: 39 },
                { Name: 'Cure Other', Level: 68, XP: 65 },
                { Name: 'Enchant Dragonstone Jewellery', Level: 68, XP: 78 },
                { Name: 'Enchant Dragonstone Bolt', Level: 68, XP: 78 },
                { Name: 'Humidify', Level: 68, XP: 65 },
                { Name: 'Teleport to Kourend', Level: 69, XP: 82 },
                { Name: 'Moonclan Teleport', Level: 69, XP: 66 },
                { Name: 'Reanimate TzHaar', Level: 69, XP: 138 },
                { Name: 'Earth Wave', Level: 70, XP: 40 },
                { Name: 'Ice Burst', Level: 70, XP: 40 },
                { Name: 'Tele Group Moonclan', Level: 70, XP: 67 },
                { Name: 'Cemetery Teleport', Level: 71, XP: 82 },
                { Name: 'Cure Me', Level: 71, XP: 69 },
                { Name: 'Hunter Kit', Level: 71, XP: 70 },
                { Name: 'Ourania Teleport', Level: 71, XP: 69 },
                { Name: 'Lassar Teleport', Level: 72, XP: 82 },                
                { Name: 'Reanimate Demon', Level: 72, XP: 144 },                
                { Name: 'Waterbirth Teleport', Level: 72, XP: 71 },
                { Name: 'Tele Group Waterbirth', Level: 73, XP: 72 },
                { Name: 'Enfeeble', Level: 73, XP: 83 },
                { Name: 'Teleother Lumbridge', Level: 74, XP: 84 },
                { Name: 'Smoke Blitz', Level: 74, XP: 42 },
                { Name: 'Cure Group', Level: 74, XP: 74 },
                { Name: 'Stat Spy', Level: 75, XP: 76 },
                { Name: 'Barbarian Teleport', Level: 75, XP: 76 },
                { Name: 'Fire Wave', Level: 75, XP: 42.5 },
                { Name: 'Tele Group Barbarian', Level: 76, XP: 77 },
                { Name: 'Shadow Blitz', Level: 76, XP: 43 },
                { Name: 'Spin Flax', Level: 76, XP: 75 },
                { Name: 'Superglass Make', Level: 77, XP: 78 },
                { Name: 'Tan Leather', Level: 78, XP: 81 },
                { Name: 'Khazard Teleport', Level: 78, XP: 80 },
                { Name: 'Dareeyak Teleport', Level: 78, XP: 88 },
                { Name: 'Resurrect Crops', Level: 78, XP: 90 },
                { Name: 'Reanimate Aviansie', Level: 78, XP: 156 },
                { Name: 'Entangle', Level: 79, XP: 89 },
                { Name: 'Tele Group Khazard', Level: 79, XP: 81 },
                { Name: 'Dream', Level: 79, XP: 82 },              
                { Name: 'Charge', Level: 80, XP: 180 },
                { Name: 'Blood Blitz', Level: 80, XP: 45 },
                { Name: 'Stun', Level: 80, XP: 90 },                
                { Name: 'String Jewellery', Level: 80, XP: 83 },
                { Name: 'Stat Restore Pot Share', Level: 81, XP: 84 },
                { Name: 'Wind Surge', Level: 81, XP: 44 },
                { Name: 'Teleother Falador', Level: 82, XP: 92 },             
                { Name: 'Magic Imbue', Level: 82, XP: 86 },
                { Name: 'Ice Blitz', Level: 82, XP: 46 },
                { Name: 'Fertile Soil', Level: 83, XP: 87 },
                { Name: 'Barrows Teleport', Level: 83, XP: 90 },
                { Name: 'Carrallangar Teleport', Level: 84, XP: 81 },
                { Name: 'Boost Potion Share', Level: 84, XP: 88 },
                { Name: 'Reanimate Abyssal Creature', Level: 85, XP: 170 },
                { Name: 'Water Surge', Level: 85, XP: 46 },
                { Name: 'Fishing Guild Teleport', Level: 85, XP: 89 },
                { Name: 'Tele Block', Level: 85, XP: 80 },
                { Name: 'Teleport to Bounty Target', Level: 85, XP: 45 },
                { Name: 'Smoke Barrage', Level: 86, XP: 48 },
                { Name: 'Tele Group Fishing Guild', Level: 86, XP: 90 },
                { Name: 'Plank Make', Level: 86, XP: 90 },
                { Name: 'Catherby Teleport', Level: 87, XP: 92 },
                { Name: 'Enchant Onyx Jewellery', Level: 87, XP: 97 },
                { Name: 'Enchant Onyx Bolt', Level: 87, XP: 97 },
                { Name: 'Shadow Barrage', Level: 88, XP: 48 },
                { Name: 'Tele Group Catherby', Level: 88, XP: 93 },
                { Name: 'Ice Plateau Teleport ', Level: 89, XP: 96 },
                { Name: 'Recharge Dragonstone', Level: 89, XP: 97.5 },
                { Name: 'Annakarl Teleport', Level: 90, XP: 100 },
                { Name: 'Earth Surge', Level: 90, XP: 48 },
                { Name: 'Tele Group Ice Plateau', Level: 90, XP: 99 },
                { Name: 'Teleother Camelot', Level: 90, XP: 100 },
                { Name: 'Ape Atoll Teleport', Level: 90, XP: 100 },
                { Name: 'Energy Transfer', Level: 91, XP: 100 },
                { Name: 'Blood Barrage', Level: 92, XP: 51 },
                { Name: 'Heal Other', Level: 92, XP: 101 },
                { Name: 'Vengeance Other', Level: 93, XP: 108 },
                { Name: 'Enchant Zenyte Jewellery', Level: 93, XP: 110 },
                { Name: 'Reanimate Dragon', Level: 93, XP: 186 },
                { Name: 'Ice Barrage', Level: 94, XP: 52 },
                { Name: 'Vengeance', Level: 94, XP: 112 },
                { Name: 'Heal Group', Level: 95, XP: 124 },
                { Name: 'Fire Surge', Level: 95, XP: 51 },
                { Name: 'Ghorrock Teleport', Level: 96, XP: 106 },
                { Name: 'Spellbook Swap', Level: 96, XP: 130 },
                          
            ]
        };
    }
    
    getMagicExperienceTable() {
        return this.experience;
    }

	
    
}
const magicXP = new MagicExperience();
export default magicXP;